name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Prettier, ESLint, and TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm --filter "./packages/**" build

      - name: Run Lint
        run: pnpm lint

      - name: Run TypeScript Check
        run: pnpm typecheck
